spring.application.name=vacas

# ===============================
# DATABASE POSTGRESQL CONFIGURATION
# ===============================

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/vacas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
#¡IMPORTANTE! Usar 'update' en producción
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional: Pool de conexiones
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5